version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node-browsers
    working_directory: ~/oshidoko
    steps:
      - checkout
      - ruby/install-deps

  rspec:
    docker:
    - image: circleci/ruby:2.7-node-browsers
    - image: circleci/mysql:5.5
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: myapp_test
        MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      MYAPP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    resource_class: small
    working_directory: ~/oshidoko
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: database setup
          command: bundle exec rails db:migrate
      - run:
          name: yarn install
          command: yarn install
      - run: bundle exec bin/webpack
      - run:
          name: run rspec
          command: bundle exec rspec

  rubocop:
    docker:
    - image: circleci/ruby:2.7-node-browsers
    - image: circleci/mysql:5.5
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: myapp_test
        MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      MYAPP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    resource_class: small
    working_directory: ~/oshidoko
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-main-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  heroku_deploy:
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: build docker image
          command: docker buildx build . --platform linux/amd64 -t $HEROKU_APP_NAME
      - run:
          name: add new tag for docker image
          command: docker tag $HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/web
      - run:
          name: push docker image
          command: docker push registry.heroku.com/$HEROKU_APP_NAME/web
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - rspec:
          requires:
            - build
      - rubocop:
          requires:
            - build
      - heroku_deploy:
          requires:
            - build
            - rspec
            - rubocop
