apiVersion: apps/v1
kind: Deployment
metadata:
  name: oshidoko-web
  namespace: oshidoko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oshidoko-web
  template:
    metadata:
      labels:
        app: oshidoko-web
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: db-migrate
          image: sakuraore/oshidoko:latest
          command: ["bundle", "exec", "rails", "db:migrate"]
          envFrom:
            - configMapRef:
                name: oshidoko-config
            - secretRef:
                name: oshidoko-secret
      containers:
        - name: web
          image: sakuraore/oshidoko:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: oshidoko-config
            - secretRef:
                name: oshidoko-secret
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: oshidoko-web-service
  namespace: oshidoko
spec:
  selector:
    app: oshidoko-web
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
